### ISSUE TITLE
Introduce simulation language for SimB 

### ISSUE THREAD

**Issue by favu100** [hhu-stups/prob-issues#121]
We could think about implementing a modeling language for simulation in SimB. The current format is JSON which is sometimes hard to use. Instead of:

```
{
    "id": "toss",
    "execute": "toss",
    "after": 500,
    "probabilisticVariables": {"c": {"Heads": "0.5", "Tails": "0.5"}},
    "activating" : "toss"
}
```

we could write

```
toss =
  EXECUTE toss
  AFTER 500
  WITH
    0.5 FOR c = Heads OR
    0.5 FOR c = Tails
  ACTIVATING toss
```

**Comment by dgelessus** [comment]
I think I've suggested this before regarding VisB, but what about YAML? That would allow a somewhat more convenient syntax without the effort of developing a completely new parser. I think Jackson supports YAML as an option instead of JSON, so it should be possible to support YAML syntax without having to change much else in the code.

```yaml
id: toss
execute: toss
after: 500
probabilisticVariables:
  c:
    Heads: "0.5"
    Tails: "0.5"
activating: toss
```
